language: go

services: 
  - docker

go: 
  - 1.12.5

notifications:
  email: false

script:
  - |
    (
      docker build . -t gin-example -f ./docker/Dockerfile
    )

after_script:
  - docker images
  - docker run -d gin-example
  - curl http://127.0.0.1:8080