language: go

services: 
  - docker

go: 
  - 1.12.5

notifications:
  email: false

script:
  - |
    (
      tag=$(git rev-parse --short HEAD)
      docker build . -t gin-example:${tag} -f ./docker/Dockerfile
      docker images
      docker run -d -p 80:8888 gin-example:${tag}

      if curl --fail http://127.0.0.1/ping ;then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker tag gin-example:${tag} jolla20i8/gin-example:${tag}
        docker tag jolla20i8/gin-example:${tag} jolla20i8/gin-example:latest
        docker push jolla20i8/gin-example:${tag}
        docker push jolla20i8/gin-example:latest
      else
        echo "test fail, please check"
        exit 1
      fi

    )
