language: go

services: 
  - docker

go: 
  - 1.12.5

notifications:
  email: false

script:
  - |
    (
      docker build . -t gin-example -f ./docker/Dockerfile
      docker images
      docker run -d -p 80:8080 gin-example
      curl --fail http://127.0.0.1/ping
    )
