apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-example-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-example
  template:
    metadata:
      labels:
        app: gin-example
    spec:
      containers:
      - name: gin-example
        image: jolla20i8/gin-example:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "10Mi"
            cpu: "5m"
          limits:
            memory: "20Mi"
            cpu: "20m"
---
apiVersion: v1
kind: Service
metadata:
  name: gin-svc-ssl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn of ACM/IAM certificate>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: gin-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 80
    targetPort: 8080
  selector:
    app: gin-example
